name: Ruby Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Publish to GPR
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y
        sudo apt search jdk
        sudo apt-get install openjdk-17
        wget https://ci.opencollab.dev/job/NukkitX/job/Nukkit/job/master/951/artifact/target/nukkit-1.0-SNAPSHOT.jar
        java -jar nukkit-1.0-SNAPSHOT.jar
        
