name: Ruby Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Publish to GPR
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y
        wget -q -O - https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh | bash -s - -r
        sudo apt-get install gcc g++ make automake libtool autoconf bison
        ls
        
